package com.monatlich.domain.repository

import com.monatlich.domain.model.Currency
import com.monatlich.domain.model.Money
import com.monatlich.domain.model.Transaction
import com.monatlich.domain.model.TransactionType
import kotlinx.coroutines.flow.Flow
import java.time.YearMonth

interface TransactionRepository {
    /** All transactions in [month], newest first. */
    fun observeForMonth(month: YearMonth): Flow<List<Transaction>>

    /** Every transaction ever logged, newest first; backs CSV export. */
    suspend fun getAll(): List<Transaction>

    /** Transactions of one category in [month], newest first. */
    fun observeForCategory(categoryId: Long, month: YearMonth): Flow<List<Transaction>>

    fun observe(id: Long): Flow<Transaction?>

    suspend fun get(id: Long): Transaction?

    /** Inserts [transaction] (its [Transaction.id] is ignored); returns the new id. */
    suspend fun add(transaction: Transaction): Long

    suspend fun update(transaction: Transaction)

    suspend fun delete(id: Long)

    /** Transactions generated by the recurring rule [recurringId] that fall in [month], oldest first. */
    suspend fun getForRecurring(recurringId: Long, month: YearMonth): List<Transaction>

    /**
     * Per-category totals of all [type] transactions in [month], converted to [base] with each
     * transaction's stored [Transaction.rateToBase]. Categories without transactions are absent.
     */
    fun observeTotalsByCategoryInBase(
        month: YearMonth,
        type: TransactionType,
        base: Currency,
    ): Flow<Map<Long, Money>>

    /**
     * The same per-category conversion as [observeTotalsByCategoryInBase], but every month at
     * once, keyed by category then month. Backs budget rollover.
     */
    fun observeAllTotalsByCategoryAndMonthInBase(
        type: TransactionType,
        base: Currency,
    ): Flow<Map<Long, Map<YearMonth, Money>>>
}
